all: clean build run

clean: # remove data and binary folder
	rm -rf data/data.json
build: # compile to binary (if you use interpreter, then do not implement it)

run: # run your binary
	python src/data.py